const PROPERTIES = [
  {
    id: 1,
    title: "Côte d'Azur Grand Residence",
    location: "Palm Jumeirah, Dubai",
    area: "Palm Jumeirah",
    price: 45000000,
    beds: 6,
    baths: 7,
    sqft: 12500,
    type: "Villa",
    status: "For Sale",
    badge: "Exclusive",
    description: "An extraordinary beachfront residence commanding sweeping panoramic views across the Arabian Gulf. This architectural masterpiece redefines luxury living on Palm Jumeirah's most coveted shoreline, where every detail has been curated for the most discerning of tastes.",
    features: ["Private Beach", "Infinity Pool", "Home Cinema", "Smart Home", "6-Car Garage", "Wine Cellar", "Staff Quarters", "Outdoor Kitchen"],
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&auto=format&fit=crop&q=80",
    year: 2022,
    garage: 6,
    furnished: true,
    view: "Arabian Gulf"
  },
  {
    id: 2,
    title: "One Palm Sky Villa",
    location: "Palm Jumeirah, Dubai",
    area: "Palm Jumeirah",
    price: 55000000,
    beds: 5,
    baths: 6,
    sqft: 9800,
    type: "Penthouse",
    status: "For Sale",
    badge: "New",
    description: "Perched atop one of the most iconic buildings on Palm Jumeirah, this sky villa offers 360-degree views of the Dubai skyline, Burj Al Arab, and the endless Arabian Gulf. Impeccably furnished with bespoke Italian finishes throughout.",
    features: ["Private Terrace", "Infinity Pool", "Smart Home", "Private Elevator", "Butler Service", "Wine Room", "Gym", "Spa"],
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&auto=format&fit=crop&q=80",
    year: 2023,
    garage: 4,
    furnished: true,
    view: "Panoramic Sea & Skyline"
  },
  {
    id: 3,
    title: "Emirates Hills Grand Mansion",
    location: "Emirates Hills, Dubai",
    area: "Emirates Hills",
    price: 85000000,
    beds: 8,
    baths: 10,
    sqft: 22000,
    type: "Mansion",
    status: "For Sale",
    badge: "Exclusive",
    description: "A palace of extraordinary proportions set within the prestigious Emirates Hills enclave. This meticulously designed estate offers unrivalled privacy, space, and luxury amidst lush landscaped grounds. A generational asset of incomparable stature.",
    features: ["Private Lake", "Tennis Court", "Cinema Room", "10-Car Garage", "Guest House", "Indoor Pool", "Spa", "Helipad"],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&auto=format&fit=crop&q=80",
    year: 2020,
    garage: 10,
    furnished: true,
    view: "Golf Course & Lake"
  },
  {
    id: 4,
    title: "Burj Khalifa Crown Penthouse",
    location: "Downtown Dubai, Dubai",
    area: "Downtown Dubai",
    price: 38000000,
    beds: 4,
    baths: 5,
    sqft: 7200,
    type: "Penthouse",
    status: "For Sale",
    badge: "Exclusive",
    description: "A crown jewel within the world's most iconic tower. This extraordinary penthouse offers a front-row seat to the Dubai Fountain show and unobstructed views of the city's magnificent skyline from every principal room.",
    features: ["Fountain Views", "Private Pool", "Smart Home", "Concierge", "Valet Parking", "Chef's Kitchen", "Entertainment Suite"],
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&auto=format&fit=crop&q=80",
    year: 2019,
    garage: 3,
    furnished: true,
    view: "Burj Khalifa & Fountain"
  },
  {
    id: 5,
    title: "Marina Pinnacle Residence",
    location: "Dubai Marina, Dubai",
    area: "Dubai Marina",
    price: 15000000,
    beds: 4,
    baths: 5,
    sqft: 5200,
    type: "Penthouse",
    status: "For Sale",
    badge: null,
    description: "Commanding the finest views across Dubai Marina, this spectacular penthouse blends contemporary design with the vibrancy of waterfront living. Floor-to-ceiling windows frame the glittering marina in every direction.",
    features: ["Marina Views", "Private Terrace", "Infinity Pool", "Gym", "Concierge", "Smart Home", "Underground Parking"],
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&auto=format&fit=crop&q=80",
    year: 2021,
    garage: 2,
    furnished: true,
    view: "Marina & Sea View"
  },
  {
    id: 6,
    title: "Jumeirah Bay Island Estate",
    location: "Jumeirah Bay Island, Dubai",
    area: "Jumeirah Bay Island",
    price: 62000000,
    beds: 6,
    baths: 7,
    sqft: 14000,
    type: "Villa",
    status: "For Sale",
    badge: "New",
    description: "Nestled on the prestigious Jumeirah Bay Island, this extraordinary waterfront estate offers the ultimate in private island living, with direct sea access and iconic Dubai skyline views framing every horizon.",
    features: ["Private Beach", "Private Jetty", "Infinity Pool", "Boathouse", "Smart Home", "Cinema", "Wellness Spa"],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&auto=format&fit=crop&q=80",
    year: 2022,
    garage: 5,
    furnished: true,
    view: "Sea & Skyline"
  },
  {
    id: 7,
    title: "Al Barari Nature Sanctuary",
    location: "Al Barari, Dubai",
    area: "Al Barari",
    price: 35000000,
    beds: 6,
    baths: 7,
    sqft: 11200,
    type: "Villa",
    status: "For Sale",
    badge: null,
    description: "Surrounded by 60% lush tropical forest, this Al Barari sanctuary is a rare fusion of nature and luxury. Set within one of Dubai's most exclusive green communities, offering profound tranquillity just minutes from the city.",
    features: ["Private Garden", "Infinity Pool", "Natural Stream", "Organic Farm", "Smart Home", "Guest Villa", "Spa"],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&auto=format&fit=crop&q=80",
    year: 2021,
    garage: 4,
    furnished: false,
    view: "Forest & Garden"
  },
  {
    id: 8,
    title: "Dubai Hills Golf Retreat",
    location: "Dubai Hills Estate, Dubai",
    area: "Dubai Hills Estate",
    price: 22000000,
    beds: 5,
    baths: 6,
    sqft: 8400,
    type: "Villa",
    status: "For Sale",
    badge: null,
    description: "Overlooking the championship golf course, this exceptional villa within Dubai Hills Estate offers an elevated lifestyle with panoramic fairway views and world-class amenities at every turn.",
    features: ["Golf Views", "Swimming Pool", "Smart Home", "Home Office", "4-Car Garage", "Maid's Room", "Landscaped Garden"],
    image: "https://images.unsplash.com/photo-1484154218962-a197022b6ac8?w=900&auto=format&fit=crop&q=80",
    year: 2022,
    garage: 4,
    furnished: false,
    view: "Golf Course"
  },
  {
    id: 9,
    title: "Earth Course Luxury Villa",
    location: "Jumeirah Golf Estates, Dubai",
    area: "Jumeirah Golf Estates",
    price: 28000000,
    beds: 6,
    baths: 7,
    sqft: 10500,
    type: "Villa",
    status: "For Sale",
    badge: null,
    description: "An architectural tour de force within Jumeirah Golf Estates, this magnificent residence offers sweeping views over the championship Earth Course with exquisitely appointed living spaces throughout.",
    features: ["Golf Frontage", "Infinity Pool", "Home Cinema", "Wine Cellar", "Gym", "Smart Home", "Guest Suite"],
    image: "https://images.unsplash.com/photo-1600210492493-0977b2a84405?w=900&auto=format&fit=crop&q=80",
    year: 2021,
    garage: 4,
    furnished: false,
    view: "Golf Course"
  },
  {
    id: 10,
    title: "MBR City Sky Collection",
    location: "Mohammed Bin Rashid City, Dubai",
    area: "MBR City",
    price: 12000000,
    beds: 3,
    baths: 4,
    sqft: 4100,
    type: "Apartment",
    status: "For Sale",
    badge: "New",
    description: "A refined collection of luxury residences within the master-planned MBR City. This superbly appointed apartment offers stunning views of the Burj Khalifa and access to world-class community amenities.",
    features: ["City Views", "Concierge", "Gym", "Infinity Pool", "Smart Home", "Underground Parking", "Children's Play Area"],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop&q=80",
    year: 2023,
    garage: 2,
    furnished: true,
    view: "City & Burj Khalifa"
  },
  {
    id: 11,
    title: "DIFC Icon Penthouse",
    location: "DIFC, Dubai",
    area: "DIFC",
    price: 18500000,
    beds: 3,
    baths: 4,
    sqft: 5600,
    type: "Penthouse",
    status: "For Sale",
    badge: "Exclusive",
    description: "Positioned at the apex of one of DIFC's most prestigious towers, this sky penthouse defines sophisticated urban living with panoramic vistas across the financial district, Downtown, and beyond.",
    features: ["City Panorama", "Private Rooftop", "Smart Home", "Wine Room", "Private Elevator", "Concierge", "Valet"],
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80",
    year: 2022,
    garage: 3,
    furnished: true,
    view: "DIFC & Downtown"
  },
  {
    id: 12,
    title: "Bluewaters Crown Penthouse",
    location: "Bluewaters Island, Dubai",
    area: "Bluewaters Island",
    price: 32000000,
    beds: 4,
    baths: 5,
    sqft: 6800,
    type: "Penthouse",
    status: "For Sale",
    badge: "New",
    description: "Occupying the entire top floor of Bluewaters Island's most iconic residential tower, this superlative penthouse frames the Ain Dubai, JBR Beach, and the open sea in breathtaking panorama.",
    features: ["Ain Dubai Views", "Private Pool", "Private Terrace", "Smart Home", "Chef's Kitchen", "Gym", "Spa"],
    image: "https://images.unsplash.com/photo-1553444836-bc0ce4b5d962?w=900&auto=format&fit=crop&q=80",
    year: 2023,
    garage: 3,
    furnished: true,
    view: "Ain Dubai & Sea"
  },
  {
    id: 13,
    title: "The World Island Retreat",
    location: "The World Islands, Dubai",
    area: "The World Islands",
    price: 95000000,
    beds: 7,
    baths: 8,
    sqft: 18500,
    type: "Villa",
    status: "For Sale",
    badge: "Exclusive",
    description: "A truly once-in-a-lifetime opportunity. This private island estate on The World Islands offers complete seclusion combined with extraordinary luxury, accessible only by private boat or helicopter.",
    features: ["Private Island", "Private Beach", "Helipad", "Private Jetty", "Infinity Pool", "Boathouse", "Staff Villa", "Spa"],
    image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=900&auto=format&fit=crop&q=80",
    year: 2020,
    garage: 4,
    furnished: true,
    view: "360° Arabian Sea"
  },
  {
    id: 14,
    title: "Palm Frond Signature Villa",
    location: "Palm Jumeirah, Dubai",
    area: "Palm Jumeirah",
    price: 28000000,
    beds: 5,
    baths: 6,
    sqft: 9500,
    type: "Villa",
    status: "For Sale",
    badge: null,
    description: "Sitting on the finest frond on Palm Jumeirah, this beautifully appointed villa offers a private beach, stunning sea views, and the quintessential Palm lifestyle just moments from the city.",
    features: ["Private Beach", "Swimming Pool", "Smart Home", "5-Car Garage", "Maid's Room", "BBQ Area", "Boat Mooring"],
    image: "https://images.unsplash.com/photo-1560185127-6a189e887acb?w=900&auto=format&fit=crop&q=80",
    year: 2018,
    garage: 5,
    furnished: false,
    view: "Sea & Atlantis"
  },
  {
    id: 15,
    title: "Downtown Fountain Residence",
    location: "Downtown Dubai, Dubai",
    area: "Downtown Dubai",
    price: 9500000,
    beds: 3,
    baths: 4,
    sqft: 3800,
    type: "Apartment",
    status: "For Sale",
    badge: null,
    description: "Commanding spectacular vistas over the Dubai Fountain and Burj Khalifa, this meticulously designed apartment represents the pinnacle of Downtown Dubai living at an exceptional address.",
    features: ["Fountain Views", "Concierge", "Gym", "Infinity Pool", "Smart Home", "2 Parking Spaces"],
    image: "https://images.unsplash.com/photo-1600047509782-20d39509f26d?w=900&auto=format&fit=crop&q=80",
    year: 2021,
    garage: 2,
    furnished: true,
    view: "Fountain & Burj Khalifa"
  },
  {
    id: 16,
    title: "Emirates Hills Palazzo",
    location: "Emirates Hills, Dubai",
    area: "Emirates Hills",
    price: 68000000,
    beds: 7,
    baths: 8,
    sqft: 17500,
    type: "Villa",
    status: "For Sale",
    badge: "Exclusive",
    description: "A landmark property in Emirates Hills' most prestigious enclave. This palatial estate seamlessly combines classical grandeur with contemporary sophistication across three immaculate levels of extraordinary living.",
    features: ["Golf Frontage", "Indoor Pool", "Cinema", "Gym", "Tennis Court", "10-Car Garage", "Guest House", "Wine Cellar"],
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=900&auto=format&fit=crop&q=80",
    year: 2019,
    garage: 10,
    furnished: true,
    view: "Golf Course & Lake"
  },
  {
    id: 17,
    title: "Marina Gate Sky Penthouse",
    location: "Dubai Marina, Dubai",
    area: "Dubai Marina",
    price: 18000000,
    beds: 4,
    baths: 5,
    sqft: 5800,
    type: "Penthouse",
    status: "For Sale",
    badge: null,
    description: "Perched above Dubai Marina, this exceptional penthouse delivers sweeping panoramic views from the shimmering marina to the open sea. Designed for the most discerning of residents who expect only the finest.",
    features: ["Marina Views", "Sea Views", "Private Pool", "Smart Home", "Concierge", "Gym", "Spa"],
    image: "https://images.unsplash.com/photo-1628744448840-60af5d0f6e38?w=900&auto=format&fit=crop&q=80",
    year: 2022,
    garage: 2,
    furnished: true,
    view: "Marina & Sea"
  },
  {
    id: 18,
    title: "Jumeirah Heritage Villa",
    location: "Jumeirah, Dubai",
    area: "Jumeirah",
    price: 24000000,
    beds: 5,
    baths: 6,
    sqft: 8800,
    type: "Villa",
    status: "For Sale",
    badge: null,
    description: "A distinguished beachside villa in the heart of Jumeirah, offering serene garden living with proximity to the finest dining, retail, and cultural experiences Dubai has to offer.",
    features: ["Beachside Location", "Private Garden", "Swimming Pool", "Smart Home", "Maid's Room", "Driver's Room", "4-Car Garage"],
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=900&auto=format&fit=crop&q=80",
    year: 2020,
    garage: 4,
    furnished: false,
    view: "Garden & Sea"
  },
  {
    id: 19,
    title: "Business Bay Canal Duplex",
    location: "Business Bay, Dubai",
    area: "Business Bay",
    price: 7200000,
    beds: 3,
    baths: 4,
    sqft: 3200,
    type: "Apartment",
    status: "For Sale",
    badge: "New",
    description: "A spectacular duplex apartment in Business Bay's most coveted residential tower, offering direct canal views and a seamlessly connected lifestyle in the heart of new Dubai's most dynamic district.",
    features: ["Canal Views", "Private Terrace", "Smart Home", "Gym", "Infinity Pool", "Concierge", "2 Parking Spaces"],
    image: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=900&auto=format&fit=crop&q=80",
    year: 2023,
    garage: 2,
    furnished: true,
    view: "Canal & Downtown"
  },
  {
    id: 20,
    title: "Al Barari Forest Mansion",
    location: "Al Barari, Dubai",
    area: "Al Barari",
    price: 48000000,
    beds: 7,
    baths: 8,
    sqft: 15000,
    type: "Mansion",
    status: "For Sale",
    badge: "Exclusive",
    description: "An enchanting forest mansion within Al Barari's legendary botanical sanctuary. This extraordinary estate represents the rarest intersection of opulent living and pristine natural beauty in Dubai.",
    features: ["Forest Setting", "Infinity Pool", "Guest Villa", "Private Stream", "Organic Garden", "Smart Home", "Spa", "Gym"],
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=900&auto=format&fit=crop&q=80",
    year: 2020,
    garage: 6,
    furnished: true,
    view: "Forest & Lakes"
  },
  {
    id: 21,
    title: "Palm Beach Townhouse",
    location: "Palm Jumeirah, Dubai",
    area: "Palm Jumeirah",
    price: 16500000,
    beds: 4,
    baths: 5,
    sqft: 5500,
    type: "Townhouse",
    status: "For Sale",
    badge: null,
    description: "A rare Palm Jumeirah townhouse with private beach access and panoramic Gulf views. Combining the intimacy of townhouse living with the unparalleled prestige and luxury of Palm Jumeirah.",
    features: ["Private Beach", "Pool", "Sea Views", "Smart Home", "Private Garden", "Direct Beach Access"],
    image: "https://images.unsplash.com/photo-1597019558161-d1fd9bdb4bb6?w=900&auto=format&fit=crop&q=80",
    year: 2021,
    garage: 2,
    furnished: false,
    view: "Sea View"
  },
  {
    id: 22,
    title: "Dubai Hills Vista Estate",
    location: "Dubai Hills Estate, Dubai",
    area: "Dubai Hills Estate",
    price: 28000000,
    beds: 6,
    baths: 7,
    sqft: 10200,
    type: "Villa",
    status: "For Sale",
    badge: null,
    description: "An outstanding contemporary villa overlooking Dubai Hills Golf Club. Set across four levels with seamless indoor-outdoor living and stunning views over the fairways and Dubai's iconic skyline.",
    features: ["Golf Views", "Infinity Pool", "Smart Home", "Home Cinema", "5-Car Garage", "Entertainment Deck", "Gym"],
    image: "https://images.unsplash.com/photo-1529408693255-c3c96dbca0e0?w=900&auto=format&fit=crop&q=80",
    year: 2023,
    garage: 5,
    furnished: false,
    view: "Golf Course"
  },
  {
    id: 23,
    title: "Golf Estates Pinnacle Villa",
    location: "Jumeirah Golf Estates, Dubai",
    area: "Jumeirah Golf Estates",
    price: 38000000,
    beds: 6,
    baths: 8,
    sqft: 13500,
    type: "Villa",
    status: "For Sale",
    badge: "Exclusive",
    description: "The crown jewel of Jumeirah Golf Estates, this exceptional villa commands the finest position on the Earth Course, with uninterrupted views, unprecedented privacy, and museum-quality finishes throughout.",
    features: ["Golf Frontage", "Infinity Pool", "Cinema Room", "8-Car Garage", "Indoor Gym", "Wine Cellar", "Staff Quarters", "Spa"],
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&auto=format&fit=crop&q=80",
    year: 2020,
    garage: 8,
    furnished: false,
    view: "Golf & Lake"
  },
  {
    id: 24,
    title: "DIFC Luxury Sky Apartment",
    location: "DIFC, Dubai",
    area: "DIFC",
    price: 8800000,
    beds: 2,
    baths: 3,
    sqft: 2800,
    type: "Apartment",
    status: "For Sale",
    badge: null,
    description: "Sophisticated urban living at its finest. This impeccably designed apartment in DIFC's premier residential tower offers the perfect balance of luxury and convenience for the modern executive.",
    features: ["City Views", "Concierge", "Smart Home", "Gym", "Pool", "Valet Parking", "Building Security"],
    image: "https://images.unsplash.com/photo-1494526585411-c5714f76ddfc?w=900&auto=format&fit=crop&q=80",
    year: 2022,
    garage: 2,
    furnished: true,
    view: "DIFC Skyline"
  },
  {
    id: 25,
    title: "MBR City Signature Penthouse",
    location: "Mohammed Bin Rashid City, Dubai",
    area: "MBR City",
    price: 19500000,
    beds: 4,
    baths: 5,
    sqft: 5600,
    type: "Penthouse",
    status: "For Sale",
    badge: "New",
    description: "A statement penthouse within MBR City's most celebrated address. Across two floors, this spectacular residence offers an outstanding collection of living spaces and unrivalled panoramic city vistas.",
    features: ["Dual-Level Layout", "Private Pool", "City Views", "Smart Home", "Concierge", "Private Elevator", "Entertainment Lounge"],
    image: "https://images.unsplash.com/photo-1440476935757-12c1c0b60c97?w=900&auto=format&fit=crop&q=80",
    year: 2023,
    garage: 3,
    furnished: true,
    view: "City & Burj"
  },
  {
    id: 26,
    title: "Emaar Beachfront Sanctuary",
    location: "Emaar Beachfront, Dubai",
    area: "Emaar Beachfront",
    price: 11000000,
    beds: 3,
    baths: 4,
    sqft: 3900,
    type: "Apartment",
    status: "For Sale",
    badge: "New",
    description: "Sitting on Dubai's most sought-after private beach community, this luminous apartment offers direct beach access, sparkling sea views, and the finest resort-style amenities on the Arabian Gulf.",
    features: ["Private Beach", "Sea Views", "Pool", "Smart Home", "Concierge", "Underground Parking", "Gym"],
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&auto=format&fit=crop&q=80",
    year: 2023,
    garage: 2,
    furnished: true,
    view: "Sea & Skyline"
  },
  {
    id: 27,
    title: "Port de La Mer Marina Penthouse",
    location: "Port de La Mer, Dubai",
    area: "Port de La Mer",
    price: 22000000,
    beds: 4,
    baths: 5,
    sqft: 6200,
    type: "Penthouse",
    status: "For Sale",
    badge: null,
    description: "Within the Mediterranean-inspired Port de La Mer, this exceptional penthouse combines the romance of harbour living with the sophistication of Dubai's finest residential standard and curated interiors.",
    features: ["Marina Views", "Private Terrace", "Pool", "Smart Home", "Concierge", "Yacht Berth Option", "Spa Access"],
    image: "https://images.unsplash.com/photo-1531088939658-1d3e67cb7f31?w=900&auto=format&fit=crop&q=80",
    year: 2022,
    garage: 2,
    furnished: true,
    view: "Marina & Sea"
  },
  {
    id: 28,
    title: "Palm Crown Estate",
    location: "Palm Jumeirah, Dubai",
    area: "Palm Jumeirah",
    price: 125000000,
    beds: 8,
    baths: 10,
    sqft: 25000,
    type: "Villa",
    status: "For Sale",
    badge: "Exclusive",
    description: "The most prestigious address on Palm Jumeirah. This monumental estate is a singular achievement in luxury residential architecture, offering a level of grandeur unmatched anywhere in Dubai or the wider region.",
    features: ["300m Private Beach", "Outdoor Cinema", "Multiple Pools", "Helipad", "Private Gym", "Spa", "12-Car Garage", "Wine Cellar", "Staff Villa"],
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&auto=format&fit=crop&q=80",
    year: 2021,
    garage: 12,
    furnished: true,
    view: "Panoramic Gulf & Skyline"
  },
  {
    id: 29,
    title: "Opera Grand Sky Penthouse",
    location: "Downtown Dubai, Dubai",
    area: "Downtown Dubai",
    price: 45000000,
    beds: 5,
    baths: 6,
    sqft: 8100,
    type: "Penthouse",
    status: "For Sale",
    badge: "Exclusive",
    description: "Adjacent to the Dubai Opera, this remarkable penthouse frames the Burj Khalifa from every angle. A rare lateral apartment with four exposures and the most coveted address in all of Downtown Dubai.",
    features: ["Burj Khalifa Views", "Opera Views", "Private Pool", "Smart Home", "Wine Room", "Private Elevator", "Concierge"],
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&auto=format&fit=crop&q=80",
    year: 2020,
    garage: 3,
    furnished: true,
    view: "Burj Khalifa & Opera"
  },
  {
    id: 30,
    title: "Dubai Creek Harbour Residences",
    location: "Dubai Creek Harbour, Dubai",
    area: "Dubai Creek Harbour",
    price: 13500000,
    beds: 3,
    baths: 4,
    sqft: 4200,
    type: "Apartment",
    status: "For Sale",
    badge: "New",
    description: "Within the visionary Dubai Creek Harbour development, this magnificent apartment previews the future of Dubai living with breathtaking views of Creek Tower and the newly emerging city district.",
    features: ["Creek Tower Views", "Creek Views", "Infinity Pool", "Smart Home", "Concierge", "Gym", "Children's Area"],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop&q=80",
    year: 2023,
    garage: 2,
    furnished: true,
    view: "Creek Tower & Skyline"
  }
];

const TEAM = [
  {
    name: "Elsa Angelo",
    title: "CEO & Founding Partner",
    bio: "With over 15 years of luxury real estate experience across Dubai and London, Elsa has guided some of the world's most discerning clients to their dream properties. Her deep knowledge of the UAE market and uncompromising dedication to client excellence have established her as one of Dubai's foremost luxury property advisors.",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80",
    phone: "+971 58 539 5932",
    email: "elsa.angelo@bhomes.com",
    languages: ["English", "Arabic", "French"]
  },
  {
    name: "Ashlin Joshy",
    title: "Head of Digital & Client Experience",
    bio: "Ashlin brings a unique perspective to luxury real estate, combining deep technological expertise with an instinctive eye for architectural excellence. As the Angelo Collection's resident innovator, he ensures every client interaction is powered by the most sophisticated property intelligence in the UAE.",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80",
    phone: "+971 50 234 5678",
    email: "ashlin@theangelo.ae",
    languages: ["English", "Malayalam", "Hindi"]
  },
  {
    name: "Marcus Flacks",
    title: "Senior Property Consultant",
    bio: "Whether Marcus is closing a AED 100M deal or delivering one of his legendary property puns, his clients know they're in the most capable — and entertaining — hands in Dubai. With an encyclopaedic knowledge of the luxury market and an infectious personality, Marcus makes every property journey truly unforgettable.",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80",
    phone: "+971 50 345 6789",
    email: "marcus@theangelo.ae",
    languages: ["English", "Afrikaans"]
  }
];

const PROPERTY_COORDS = {
  1:  [25.1129, 55.1389],
  2:  [25.1150, 55.1410],
  3:  [25.0680, 55.1640],
  4:  [25.1951, 55.2735],
  5:  [25.0805, 55.1403],
  6:  [25.2070, 55.2424],
  7:  [25.0977, 55.3618],
  8:  [25.1061, 55.2442],
  9:  [25.0230, 55.1466],
  10: [25.1855, 55.2975],
  11: [25.2112, 55.2817],
  12: [25.0808, 55.1220],
  13: [25.1074, 55.1684],
  14: [25.1100, 55.1350],
  15: [25.1972, 55.2750],
  16: [25.0695, 55.1658],
  17: [25.0820, 55.1420],
  18: [25.2093, 55.2420],
  19: [25.1888, 55.2680],
  20: [25.0990, 55.3630],
  21: [25.1080, 55.1370],
  22: [25.1040, 55.2460],
  23: [25.0215, 55.1480],
  24: [25.2120, 55.2830],
  25: [25.1865, 55.2990],
  26: [25.0902, 55.1298],
  27: [25.2197, 55.3082],
  28: [25.1140, 55.1395],
  29: [25.1960, 55.2742],
  30: [25.2170, 55.3568],
};

const TESTIMONIALS = [
  {
    quote: "The Angelo Collection elevated every aspect of our property search. Elsa's intimate knowledge of Palm Jumeirah was extraordinary — she found us a villa that didn't even reach the open market. Their discretion and professionalism are truly world-class.",
    name: "James & Sophia Whitfield",
    detail: "Purchased Palm Jumeirah Villa, AED 45M",
    photo: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80"
  },
  {
    quote: "As someone who has purchased property across London, Monaco, and Dubai, I can say with certainty that The Angelo Collection operates at a different level entirely. Their market intelligence, combined with their extraordinary network, is unmatched.",
    name: "Alessandro Romano",
    detail: "Purchased Emirates Hills Mansion, AED 68M",
    photo: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80"
  },
  {
    quote: "When we relocated from Singapore, we needed more than a property agent — we needed partners who understood our lifestyle. The Angelo team not only found our perfect home but guided us through every step with warmth and expertise.",
    name: "Priya & Raj Sharma",
    detail: "Purchased Dubai Hills Villa, AED 28M",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80"
  },
  {
    quote: "I've worked with luxury real estate agencies globally, and The Angelo Collection stands apart. Their attention to detail is extraordinary — they presented only properties that precisely matched my criteria. Not a minute of my time was wasted.",
    name: "Charlotte Beaumont",
    detail: "Purchased Downtown Penthouse, AED 38M",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&auto=format&fit=crop&q=80"
  },
  {
    quote: "Marcus made the entire journey seamless — and highly entertaining. His knowledge of the off-plan market gave us a significant investment advantage. We purchased three units on his recommendation and the returns have been exceptional.",
    name: "Thomas Brennan",
    detail: "Investment Portfolio, AED 52M",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80"
  },
  {
    quote: "The Angelo Collection handled the sale of our Jumeirah Bay property with extraordinary care. They secured a price 12% above our initial valuation through their curated off-market network. Simply outstanding in every respect.",
    name: "Fatima Al-Rashid",
    detail: "Sold Jumeirah Bay Island Villa, AED 58M",
    photo: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=200&auto=format&fit=crop&q=80"
  },
  {
    quote: "From our very first phone call, the service was unlike anything we had experienced before. Every question answered instantly, every concern addressed before we even voiced it. The Angelo Collection didn't just find us a home — they found us exactly the right one.",
    name: "Daniel & Claire Morrison",
    detail: "Purchased Dubai Hills Villa, AED 18M",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80"
  },
  {
    quote: "What sets The Angelo Collection apart isn't just their knowledge of the market — it's the warmth of the people. The team genuinely cared about us as a family, not just as a transaction. We felt supported every single step of the way.",
    name: "Nadia Al-Farsi",
    detail: "Purchased Emaar Beachfront Apartment, AED 11M",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80"
  },
  {
    quote: "I've worked with the biggest names in real estate across three continents. The Angelo Collection is, without question, the finest agency I have ever engaged with. The professionalism, the results, and the sheer quality of the experience are in a class of their own.",
    name: "Jonathan Hartley",
    detail: "Investment Portfolio, AED 75M",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80"
  },
  {
    video: "videos/ashlin-testimonial.mov",
    name: "Ashlin",
    detail: "Client, The Angelo Collection",
    photo: ""
  }
];
